### PR TITLE
Fix phpcs config file

### PR DESCRIPTION
**Pull request by pereirinha**
Addresses https://github.com/cloudinary/cloudinary_wordpress/issues/791

### CODE REVIEW

**Review by GaryJones — APPROVED** [review]
In terms of adding PHPCompatibilityWP, this is ✅.

However, note that the current release of PHPCompatibilityWP uses a version of PHPCompatibility that does NOT include the PHP 8-related sniffs, which are only in the `develop` branch of `PHPCompatibility`, so [further tweaks](https://docs.wpvip.com/how-tos/code-scanning-for-php-upgrade/#Upcoming-releases-of-PHPCompatibility) would be needed if checking for PHP 8 compatibility is what's desired.

**Comment by pereirinha** [comment]
Thanks again, @GaryJones, for pointing out further improvements.
I did update both PRs, so they should now fully cover the upcoming PHPCompatibility 10.

I'll keep an eye on it so that when it's out, we can update our code base accordingly.

Can you please do just a sanity check here to validate ahead of merging it? Much appreciated.

**Review by GaryJones — APPROVED** [review]
Looks good to me!

**Comment by pereirinha** [comment]
Thank you @GaryJones.
Merging.

**Pull request merged**
