### PR TITLE
enable image and video optimisations

### PR DESCRIPTION
**Pull request by DavidCramer**

### CODE REVIEW

**Comment by pereirinha** [comment]
@DavidCramer 

Codewise, things look good, but I've found a problem while testing the functionality.
Please, check the backchannel.

**Comment by DavidCramer** [comment]
@pereirinha - addressed issues, and found another issue which I addressed ;)

**Review by pereirinha — COMMENTED** [review]
@DavidCramer left you a comment

**Review by pereirinha — APPROVED** [review]
Looks great @DavidCramer 

Like in the other PR, I merged develop in, resolved the conflicts, so we can have this going.

Can you double-check if nothing is changed?

Thank you

**Pull request merged**
